TELEGRAM_BOT_TOKEN = 'YOUR_BOT_TOKEN_HERE'
ALLOWED_USERS_FILE = 'allowed_users.json'
EMA_PERIOD = 21
LOG_TO_TERMINAL = True

MT5_LOGIN = 12345678
MT5_PASSWORD = "your_password"
MT5_SERVER = "Exness-MT5Trial6"